export const SELLER_AUTH_STATUS = {
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
  REVOKED: 3,
}

export const SELLER_AUTH_STATUS_LABEL_MAP = {
  [SELLER_AUTH_STATUS.PENDING]: '待审核',
  [SELLER_AUTH_STATUS.APPROVED]: '已通过',
  [SELLER_AUTH_STATUS.REJECTED]: '已驳回',
  [SELLER_AUTH_STATUS.REVOKED]: '已撤回',
}
